name: Release Packages

on:
  push:
    branches:
      - main # Only run on push to the main branch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x # Use your preferred Node.js version

      # Step 3: Install dependencies for all packages in the Turborepo
      - name: Install Dependencies
        run: npm install

      # Step 4: Setup Turborepo Cache
      - name: Setup Turborepo
        run: npx turbo run build --filter=packages/node # Customize this to target the specific package

      # Step 5: Run Tests (if applicable)
      - name: Run Tests
        run: npm test # Customize if needed

      # Step 6: Create Release Pull Request or Publish to npm using Changesets
      - name: Create Release PR or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm # Automatically publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Your npm authentication token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for PRs

      # Step 7: Navigate to the package directory and publish to npm
      - name: Publish to npm
        if: steps.changesets.outputs.published == 'true'
        run: |
          cd packages/node  # Navigate to the package you want to publish
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
